### PR TITLE
B18 update, queued jobs, prisoner interaction mod

### PR DESCRIPTION
**Pull request by Mehni**
This pull request consist of three commits.

- @mastertea's update to B18.

- a feature addition by me to optionally show the new Queued jobs added in B18.

- a bug fix for an issue that was present when trying to view the prisoner interaction mode.

### CODE REVIEW

**Comment by WaKeMaTTa** [comment]
Can you add a description about your changes. Thank you :heart:

**Comment by Mehni** [comment]
Done.

**Comment by WaKeMaTTa** [comment]
@koisama can you merge and release a new version ?

**Comment by Mehni** [comment]
@WaKeMaTTa It's been half a year so I'm closing this pull request as I believe koisama is no longer interested in maintaining the mod.

I've uploaded a 1.0 version of Numbers on [Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=1414302321) and on the GitHub this pull request originated from.

Thank you koisama, for the awesome mod.

**Pull request closed without merging**
